/**
 */
package org.palladiosimulator.scalablepcmgroups.provider;

import java.util.ArrayList;
import java.util.Collection;

import org.eclipse.emf.common.notify.Adapter;
import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.Notifier;

import org.eclipse.emf.edit.provider.ChangeNotifier;
import org.eclipse.emf.edit.provider.ComposeableAdapterFactory;
import org.eclipse.emf.edit.provider.ComposedAdapterFactory;
import org.eclipse.emf.edit.provider.IChangeNotifier;
import org.eclipse.emf.edit.provider.IDisposable;
import org.eclipse.emf.edit.provider.IEditingDomainItemProvider;
import org.eclipse.emf.edit.provider.IItemLabelProvider;
import org.eclipse.emf.edit.provider.IItemPropertySource;
import org.eclipse.emf.edit.provider.INotifyChangedListener;
import org.eclipse.emf.edit.provider.IStructuredItemContentProvider;
import org.eclipse.emf.edit.provider.ITreeItemContentProvider;

import org.palladiosimulator.scalablepcmgroups.util.scalablepcmgroupsAdapterFactory;

/**
 * This is the factory that is used to provide the interfaces needed to support Viewers.
 * The adapters generated by this factory convert EMF adapter notifications into calls to {@link #fireNotifyChanged fireNotifyChanged}.
 * The adapters also support Eclipse property sheets.
 * Note that most of the adapters are shared among multiple instances.
 * <!-- begin-user-doc -->
 * <!-- end-user-doc -->
 * @generated
 */
public class scalablepcmgroupsItemProviderAdapterFactory extends scalablepcmgroupsAdapterFactory implements ComposeableAdapterFactory, IChangeNotifier, IDisposable {
    /**
     * This keeps track of the root adapter factory that delegates to this adapter factory.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected ComposedAdapterFactory parentAdapterFactory;

    /**
     * This is used to implement {@link org.eclipse.emf.edit.provider.IChangeNotifier}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected IChangeNotifier changeNotifier = new ChangeNotifier();

    /**
     * This keeps track of all the supported types checked by {@link #isFactoryForType isFactoryForType}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected Collection<Object> supportedTypes = new ArrayList<Object>();

    /**
     * This constructs an instance.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    public scalablepcmgroupsItemProviderAdapterFactory() {
        supportedTypes.add(IEditingDomainItemProvider.class);
        supportedTypes.add(IStructuredItemContentProvider.class);
        supportedTypes.add(ITreeItemContentProvider.class);
        supportedTypes.add(IItemLabelProvider.class);
        supportedTypes.add(IItemPropertySource.class);
    }

    /**
     * This keeps track of the one adapter used for all {@link org.palladiosimulator.scalablepcmgroups.ScalablePCMGroups} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected ScalablePCMGroupsItemProvider scalablePCMGroupsItemProvider;

    /**
     * This creates an adapter for a {@link org.palladiosimulator.scalablepcmgroups.ScalablePCMGroups}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public Adapter createScalablePCMGroupsAdapter() {
        if (scalablePCMGroupsItemProvider == null) {
            scalablePCMGroupsItemProvider = new ScalablePCMGroupsItemProvider(this);
        }

        return scalablePCMGroupsItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link org.palladiosimulator.scalablepcmgroups.InfrastructureGroup} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected InfrastructureGroupItemProvider infrastructureGroupItemProvider;

    /**
     * This creates an adapter for a {@link org.palladiosimulator.scalablepcmgroups.InfrastructureGroup}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public Adapter createInfrastructureGroupAdapter() {
        if (infrastructureGroupItemProvider == null) {
            infrastructureGroupItemProvider = new InfrastructureGroupItemProvider(this);
        }

        return infrastructureGroupItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link org.palladiosimulator.scalablepcmgroups.ServiceGroup} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected ServiceGroupItemProvider serviceGroupItemProvider;

    /**
     * This creates an adapter for a {@link org.palladiosimulator.scalablepcmgroups.ServiceGroup}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public Adapter createServiceGroupAdapter() {
        if (serviceGroupItemProvider == null) {
            serviceGroupItemProvider = new ServiceGroupItemProvider(this);
        }

        return serviceGroupItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link org.palladiosimulator.scalablepcmgroups.CompetingConsumersGroup} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected CompetingConsumersGroupItemProvider competingConsumersGroupItemProvider;

    /**
     * This creates an adapter for a {@link org.palladiosimulator.scalablepcmgroups.CompetingConsumersGroup}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public Adapter createCompetingConsumersGroupAdapter() {
        if (competingConsumersGroupItemProvider == null) {
            competingConsumersGroupItemProvider = new CompetingConsumersGroupItemProvider(this);
        }

        return competingConsumersGroupItemProvider;
    }

    /**
     * This keeps track of the one adapter used for all {@link org.palladiosimulator.scalablepcmgroups.Queue} instances.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    protected QueueItemProvider queueItemProvider;

    /**
     * This creates an adapter for a {@link org.palladiosimulator.scalablepcmgroups.Queue}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public Adapter createQueueAdapter() {
        if (queueItemProvider == null) {
            queueItemProvider = new QueueItemProvider(this);
        }

        return queueItemProvider;
    }

    /**
     * This returns the root adapter factory that contains this factory.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public ComposeableAdapterFactory getRootAdapterFactory() {
        return parentAdapterFactory == null ? this : parentAdapterFactory.getRootAdapterFactory();
    }

    /**
     * This sets the composed adapter factory that contains this factory.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public void setParentAdapterFactory(ComposedAdapterFactory parentAdapterFactory) {
        this.parentAdapterFactory = parentAdapterFactory;
    }

    /**
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public boolean isFactoryForType(Object type) {
        return supportedTypes.contains(type) || super.isFactoryForType(type);
    }

    /**
     * This implementation substitutes the factory itself as the key for the adapter.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public Adapter adapt(Notifier notifier, Object type) {
        return super.adapt(notifier, this);
    }

    /**
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public Object adapt(Object object, Object type) {
        if (isFactoryForType(type)) {
            Object adapter = super.adapt(object, type);
            if (!(type instanceof Class<?>) || (((Class<?>)type).isInstance(adapter))) {
                return adapter;
            }
        }

        return null;
    }

    /**
     * This adds a listener.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public void addListener(INotifyChangedListener notifyChangedListener) {
        changeNotifier.addListener(notifyChangedListener);
    }

    /**
     * This removes a listener.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public void removeListener(INotifyChangedListener notifyChangedListener) {
        changeNotifier.removeListener(notifyChangedListener);
    }

    /**
     * This delegates to {@link #changeNotifier} and to {@link #parentAdapterFactory}.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public void fireNotifyChanged(Notification notification) {
        changeNotifier.fireNotifyChanged(notification);

        if (parentAdapterFactory != null) {
            parentAdapterFactory.fireNotifyChanged(notification);
        }
    }

    /**
     * This disposes all of the item providers created by this factory. 
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    @Override
    public void dispose() {
        if (scalablePCMGroupsItemProvider != null) scalablePCMGroupsItemProvider.dispose();
        if (infrastructureGroupItemProvider != null) infrastructureGroupItemProvider.dispose();
        if (serviceGroupItemProvider != null) serviceGroupItemProvider.dispose();
        if (competingConsumersGroupItemProvider != null) competingConsumersGroupItemProvider.dispose();
        if (queueItemProvider != null) queueItemProvider.dispose();
    }

}
